apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
    cloud.google.com/neg: '{"ingress":false}'
  name: ceramic
spec:
  ports:
    - name: api
      port: 7007
      protocol: TCP
      targetPort: 7007
  selector:
    app: ceramic
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceramic
spec:
  defaultBackend:
    service:
      name: ceramic
      port:
        number: 7007
