---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: composedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composedb
  template:
    metadata:
      labels:
        app: composedb
    spec:
      containers:
        - name: composedb
          image: ceramicnetwork/composedb:develop
          command:
            - node
            - scripts/run.mjs
          ports:
            - name: graphql
              containerPort: 4000
            - name: ui
              containerPort: 3000
          env:
            - name: CAS_API_URL
              valueFrom:
                configMapKeyRef:
                  name: ceramic-env
                  key: CAS_API_URL
            - name: CERAMIC_ADMIN_SEED
              valueFrom:
                secretKeyRef:
                  name: ceramic-admin
                  key: private-key
            - name: CERAMIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: ceramic-env
                  key: CERAMIC_API_URL
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
