---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: composedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composedb
  template:
    metadata:
      labels:
        app: composedb
    spec:
      containers:
        - name: composedb
          image: ceramicnetwork/composedb:develop
          command:
            - /bin/bash
            - -c
            - "sleep infinity"
          ports:
            - containerPort: 7007
          env:
            - name: CAS_API_URL
              value: "https://cas-clay.3boxlabs.com"
            - name: CERAMIC_ADMIN_SEED
              value: c3160737834462291667e3b57a7a413f39440e503db5cb2d5c6943e700cf090e
            - name: CERAMIC_API_URL
              value: http://ceramic:7007
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
